 
// Generated helper templates
// Zirpl.MusicChecker.Model\_auto\AppTransform.txt4
// Zirpl.MusicChecker.Model\_auto\Subscriptions\AppTransform.txt4
// Zirpl.MusicChecker.Model\_auto\Settings\AppTransform.txt4
// Zirpl.MusicChecker.Model\_auto\Promotions\AppTransform.txt4
// Zirpl.MusicChecker.Model\_auto\Partners\AppTransform.txt4
// Zirpl.MusicChecker.Model\_auto\Orders\AppTransform.txt4
// Zirpl.MusicChecker.Model\_auto\Notifications\AppTransform.txt4
// Zirpl.MusicChecker.Model\_auto\Membership\AppTransform.txt4
// Zirpl.MusicChecker.Model\_auto\Customers\AppTransform.txt4
// Zirpl.MusicChecker.Model\_auto\Catalog\AppTransform.txt4
// Generated items
// Zirpl.MusicChecker.Model\_auto\Tag.auto.cs
// Zirpl.MusicChecker.Model\_auto\Subscriptions\SubscriptionStatusType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Subscriptions\SubscriptionPeriodType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Subscriptions\SubscriptionPeriod.auto.cs
// Zirpl.MusicChecker.Model\_auto\Subscriptions\SubscriptionInstance.auto.cs
// Zirpl.MusicChecker.Model\_auto\Subscriptions\Subscription.auto.cs
// Zirpl.MusicChecker.Model\_auto\Subscriptions\PendingSubscriptionChange.auto.cs
// Zirpl.MusicChecker.Model\_auto\Settings\TaxRule.auto.cs
// Zirpl.MusicChecker.Model\_auto\Settings\SystemSetting.auto.cs
// Zirpl.MusicChecker.Model\_auto\Settings\StateProvinceType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Promotions\Referral.auto.cs
// Zirpl.MusicChecker.Model\_auto\Promotions\PromoCode.auto.cs
// Zirpl.MusicChecker.Model\_auto\Promotions\DiscountApplicabilityType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Promotions\DiscountAmountType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Promotions\Discount.auto.cs
// Zirpl.MusicChecker.Model\_auto\Partners\PartnerReferralPlan.auto.cs
// Zirpl.MusicChecker.Model\_auto\Partners\PartnerReferralCouponRequestStatusType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Partners\PartnerReferralCouponRequest.auto.cs
// Zirpl.MusicChecker.Model\_auto\Partners\PartnerReferral.auto.cs
// Zirpl.MusicChecker.Model\_auto\Partners\Partner.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\SubscriptionOrderItemType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\SubscriptionOrderItem.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\StripeCustomerChargeOption.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\StripeCharge.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\ShoppingCartItem.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\OrderStatusType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\OrderItem.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\OrderChargeStatusType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\Order.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\DiscountUsageRestrictionType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\DiscountUsage.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\ChargeType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\ChargeStatusType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\ChargeMethodType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Orders\Charge.auto.cs
// Zirpl.MusicChecker.Model\_auto\Notifications\EmailEventType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Notifications\EmailEvent.auto.cs
// Zirpl.MusicChecker.Model\_auto\NameSuffixType.auto.cs
// Zirpl.MusicChecker.Model\_auto\NamePrefixType.auto.cs
// Zirpl.MusicChecker.Model\_auto\Membership\Visitor.auto.cs
// Zirpl.MusicChecker.Model\_auto\Membership\PasswordResetLink.auto.cs
// Zirpl.MusicChecker.Model\_auto\Customers\CustomerTag.auto.cs
// Zirpl.MusicChecker.Model\_auto\Customers\CustomerReferral.auto.cs
// Zirpl.MusicChecker.Model\_auto\Customers\CustomerChargeOption.auto.cs
// Zirpl.MusicChecker.Model\_auto\Customers\Customer.auto.cs
// Zirpl.MusicChecker.Model\_auto\Catalog\TierShipment.auto.cs
// Zirpl.MusicChecker.Model\_auto\Catalog\TierPrice.auto.cs
// Zirpl.MusicChecker.Model\_auto\Catalog\SubscriptionChoiceTierPriceCombination.auto.cs
// Zirpl.MusicChecker.Model\_auto\Catalog\SubscriptionChoice.auto.cs
// Zirpl.MusicChecker.Model\_auto\Catalog\ProductReview.auto.cs
// Zirpl.MusicChecker.Model\_auto\Catalog\DisplayProduct.auto.cs
// Zirpl.MusicChecker.Model\_auto\Catalog\Category.auto.cs
// Zirpl.MusicChecker.Model\_auto\Catalog\Brand.auto.cs
// Zirpl.MusicChecker.Model\_auto\Address.auto.cs
